### get all students
GET http://localhost:8080/api/students

### add student
POST http://localhost:8080/api/students
Content-Type: application/json

{
     "name":"Muhammad Rehan",
    "email":"rehan@gmail.com",
    "course":"Math"
}

### Delete
DELETE http://localhost:8080/api/students/1

### update the student
PUT http://localhost:8080/api/students/2
Content-Type: application/json

{
  "name": "Rehan azam"
}

###
PATCH http://localhost:8080/api/students/2
Content-Type: application/json

{
  "name": "Rana rehan"
}